### ISSUE TITLE
[BUG] Find threshold using density method  NameError: name 'ncpu_' is not defined

### ISSUE THREAD

**Issue by jisnoalia** [zktuong/dandelion#149] opened 2022-05-20 16:20 UTC
**Describe the bug**
When I  run  the step in the tutorial  BCRclustering,
~~~~python
ddl.pp.calculate_threshold(vdj)
~~~~~
get thi error
~~~~python
   2523                                         model=model_,
-> 2524                                         nproc=ncpu_,
   2525                                         **kwargs)

NameError: name 'ncpu_' is not defined
~~~~

**To Reproduce**

**Expected behavior**

**Screenshots**
![image-20220521002037833](https://raw.githubusercontent.com/jisnoalia/image/master/img/202205210020933.png)

**Desktop (please complete the following information):**
 - OS: linux ubuntu 
 - dandelion==0.2.0 pandas==1.3.5 numpy==1.21.5 matplotlib==3.5.1 networkx==2.6.3 scipy==1.7.3 skbio==0.5.7

**Additional context**

**Comment by zktuong** [comment] 2022-05-20 16:22
Thanks @jisnoalia i found this bug yesterday and it's now fixed in v0.2.1 on pypi 

do `pip install sc-dandelion -U` and it should now work properly.

**Comment by jisnoalia** [comment] 2022-05-21 04:15
After `pip install sc-dandelion -U`, I get a new error. ![image-20220521121338037](https://raw.githubusercontent.com/jisnoalia/image/master/img/202205211213110.png) and ![](https://raw.githubusercontent.com/jisnoalia/image/master/img/202205211214106.png).
I installed packages in a conda environment, but the dandelion might use the default libpath. how can I change the libpaths in jupyter.

**Comment by zktuong** [comment] 2022-05-21 04:29
So the new issue could be related to your R package/library folder isn't picked up properly.

Can you tell me whether "alakazam" and "shazam" are installed in R?

**Comment by jisnoalia** [comment] 2022-05-21 04:44
"alakazam" and "shazam" are installed in my conda environment. 
![image-20220521123908091](https://raw.githubusercontent.com/jisnoalia/image/master/img/202205211239135.png)

![image-20220521123944532](https://raw.githubusercontent.com/jisnoalia/image/master/img/202205211239566.png)
I don't know how to use the packages in conda through the jupyter.

**Comment by zktuong** [comment] 2022-05-21 04:46
i see. did you do `pip install rpy2` or `conda install rpy2`?

**Comment by jisnoalia** [comment] 2022-05-21 04:48
Yes, it already was installed in my environment.
![image-20220521124723327](https://raw.githubusercontent.com/jisnoalia/image/master/img/202205211247359.png)

**Comment by jisnoalia** [comment] 2022-05-21 04:55
I restart my kernel ,and run ddl.pp.calculate_threshold(vdj) again .
It only show the error 
![image-20220521125238363](https://raw.githubusercontent.com/jisnoalia/image/master/img/202205211252446.png)

**Comment by zktuong** [comment] 2022-05-21 04:58
OK. the issue is that your R packages (`shazam` and `alakazam`) are currently managed by `conda`, whereas your `rpy2` is linked to the base conda (installed from `apt`) as you installed it with `pip`. So your options are:

1) remove `conda`'s R installation e.g. `conda remove r-base`
This will remove all traces of R and R packages that was managed by `conda`.
Then open up `R` from terminal manusally, and doing a manual install of the packages:
`install.packages(c('alakazam', 'shazam'))`
This should hopefully install your packages into somewhere that `rpy2` can see (`/usr/lib/R/site-library` or somewhere similar - you will know where it is if you open up R and type `.libPaths()`).

2) remove your current `rpy2` installed with `pip` and then do `conda install rpy2`
this should then hopefully let your new `rpy2` see where `shazam` and `alakazam` are currently installed.
I prefer the first option because I don't like to use conda to manage R but some people do.

**Comment by zktuong** [comment] 2022-05-21 05:17
oh can you also downgrade you `rpy2` to `3.4.2`?

**Comment by jisnoalia** [comment] 2022-05-21 05:51
Hooray， I install 'alakazam', and 'shazam' to my libPaths and downgrade my rpy2 to 3.4.2. My problem was solved. Thank you for your guidance. I started to learn the subsequent steps。

**Comment by zktuong** [comment] 2022-05-21 05:53
fantastic! hope you enjoy the package =) i'll close this issue now.

**Closed by zktuong** 2022-05-21 05:53 UTC
Labels: bug
